version: "0.5"

processes:
  clickhouse:
    command: clickhouse-server
    readiness_probe:
      exec:
        command: clickhouse-client --query "SELECT 1"
      initial_delay_seconds: 5
      period_seconds: 5
      timeout_seconds: 2
      success_threshold: 1
      failure_threshold: 3

  graphql:
    command: ./scripts/with-dotenv.sh --log-file logs/graphql.log -- bun run packages/map-graphql/src/index.ts
    depends_on:
      clickhouse:
        condition: process_healthy
  scraper:
    command: ./scripts/with-dotenv.sh --log-file logs/scraper.log -- bun run packages/map-scraper/src/index.ts
    depends_on:
      clickhouse:
        condition: process_healthy
      graphql:
        condition: process_started
  frontend:
    command: ./scripts/with-dotenv.sh --chdir packages/map-frontend --log-file logs/frontend.log -- env PATH=./node_modules/.bin:$PATH bun run dev
    depends_on:
      graphql:
        condition: process_started
